.Dd
.Dt HELLO 8
.Os BSD
.Sh NAME
.Nm hello
.Nd greet the world
.\"
.Sh SYNOPSIS
.Nm
prints a funny message on standard output.
.Nm
does not care about its command line.
.\"
.Sh RETURN VALUES
.Nm
returns a magic value that depends on the system and, some
say, on the current likes of God.
.\"
.Sh SEE ALSO
.Xr world 8
