.Dd Dec. 12 2021
.Dt HELLOWOLRD 8
.Os BSD
.Sh NAME
.Nm helloworld.sh
.Nd a refined decision support system for your day
.\"
.Sh SYNOPSIS 
.Nm
tells you what approach is best for the current day.
.Pp
.Nm 
decision variables are not known to humans, but many people report an improvement in the personal productivity and in the quality of life after starting using it.
.\"
.Sh SEE ALSO
.Xr hello 8 ,
.Xr world 8
